### ISSUE TITLE
出力が大きいとエラー

### ISSUE THREAD

**Issue by n4o847** [n4o847/nazuki-hs#1]
Web 版で、出力長が 60000 ~ 70000 bytes くらいになると止まってしまう。

`mul` が 70000 bytes 以上あるため使えなくなってしまう。

エラーが出るときもある。

```
JSException "RuntimeError: table index is out of bounds\n    at <anonymous>:wasm-function[7045]:0x15eb02\n    at scheduleTSO (<anonymous>:wasm-function[7046]:0x15eb2f)\n    at dt.tick (http://localhost:8080/main.js:2:335194)\n    at http://localhost:8080/main.js:2:332614\n    at http://localhost:8080/main.js:2:321379\n    at p (http://localhost:8080/main.js:2:321494)\n    at a (http://localhost:8080/main.js:2:320852)"
```

```
RuntimeError: table index is out of bounds
    at <anonymous>:wasm-function[7045]:0x15eb02
    at scheduleTSO (<anonymous>:wasm-function[7046]:0x15eb2f)
    at dt.tick (http://localhost:8080/main.js:2:335194)
    at http://localhost:8080/main.js:2:332614
    at http://localhost:8080/main.js:2:321379
    at p (http://localhost:8080/main.js:2:321494)
    at a (http://localhost:8080/main.js:2:320852)
```

**Comment by n4o847** [comment]
`State.Strict` と `modify'` を使うようにしたらかなり耐えるようになった。

commit: 2668584

再発の可能性があるので建てたままにしておく。

**Comment by n4o847** [comment]
```
scan
scan
mul
print
```

をアセンブルした結果

- `State.Strict` と `modify'`

```
    131,576,952 bytes allocated in the heap
    142,408,608 bytes copied during GC
    30,161,920 bytes maximum residency (7 sample(s))
        832,512 bytes maximum slop
            28 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
Gen  0       119 colls,   119 par    0.242s   0.058s     0.0005s    0.0045s
Gen  1         7 colls,     6 par    0.342s   0.072s     0.0103s    0.0360s

Parallel GC work balance: 5.83% (serial 0%, perfect 100%)

TASKS: 26 (1 bound, 25 peak workers (25 total), using -N12)

SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

INIT    time    0.009s  (  0.004s elapsed)
MUT     time    0.107s  (  0.064s elapsed)
GC      time    0.584s  (  0.129s elapsed)
RP      time    0.000s  (  0.000s elapsed)
PROF    time    0.000s  (  0.000s elapsed)
EXIT    time    0.002s  (  0.001s elapsed)
Total   time    0.702s  (  0.199s elapsed)

Alloc rate    1,235,290,353 bytes per MUT second

Productivity  15.2% of total user, 32.4% of total elapsed
```

- `State` と `modify`

```
    238,828,640 bytes allocated in the heap
    235,785,488 bytes copied during GC
    62,396,376 bytes maximum residency (11 sample(s))
    66,332,712 bytes maximum slop
            59 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
Gen  0       178 colls,   178 par    0.581s   0.114s     0.0006s    0.0034s
Gen  1        11 colls,    10 par    1.423s   0.210s     0.0191s    0.0636s

Parallel GC work balance: 3.19% (serial 0%, perfect 100%)

TASKS: 26 (1 bound, 25 peak workers (25 total), using -N12)

SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

INIT    time    0.001s  (  0.004s elapsed)
MUT     time    0.283s  (  0.121s elapsed)
GC      time    2.004s  (  0.325s elapsed)
RP      time    0.000s  (  0.000s elapsed)
PROF    time    0.000s  (  0.000s elapsed)
EXIT    time    0.002s  (  0.001s elapsed)
Total   time    2.291s  (  0.451s elapsed)

Alloc rate    843,586,579 bytes per MUT second

Productivity  12.4% of total user, 26.9% of total elapsed
```

**Comment by n4o847** [comment]
- `StrictData`

```
    100,860,536 bytes allocated in the heap
    24,962,496 bytes copied during GC
      4,565,312 bytes maximum residency (6 sample(s))
        218,816 bytes maximum slop
              4 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
Gen  0        90 colls,    90 par    0.056s   0.012s     0.0001s    0.0012s
Gen  1         6 colls,     5 par    0.053s   0.012s     0.0020s    0.0073s

Parallel GC work balance: 18.06% (serial 0%, perfect 100%)

TASKS: 26 (1 bound, 25 peak workers (25 total), using -N12)

SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

INIT    time    0.000s  (  0.004s elapsed)
MUT     time    0.096s  (  0.056s elapsed)
GC      time    0.109s  (  0.024s elapsed)
RP      time    0.000s  (  0.000s elapsed)
PROF    time    0.000s  (  0.000s elapsed)
EXIT    time    0.003s  (  0.001s elapsed)
Total   time    0.208s  (  0.085s elapsed)

Alloc rate    1,052,911,892 bytes per MUT second

Productivity  46.1% of total user, 66.1% of total elapsed
```
